version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - mysql
        command: php artisan serve --host=0.0.0.0 --port=8000
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: bakerzbite
            DB_USERNAME: root
            DB_PASSWORD:

    mysql:
        image: mysql:5.7
        container_name: laravel-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: bakerzbite
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        command: --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"

volumes:
    mysql_data:
